<?php

return [
    'name'     => env('APP_NAME', 'VelvetHour'),
    'env'      => env('APP_ENV', 'production'),
    'debug'    => (bool) env('APP_DEBUG', false),
    'url'      => env('APP_URL', 'http://localhost'),
    'timezone' => 'Asia/Tashkent',
    'locale'   => 'en',
    'key'      => env('APP_KEY'),
    'cipher'   => 'AES-256-CBC',

    'providers' => [
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Notifications\NotificationServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,
        PHPOpenSourceSaver\JWTAuth\Providers\LaravelServiceProvider::class,
        App\Providers\AppServiceProvider::class,
    ],

    'aliases' => [
        'App'     => Illuminate\Support\Facades\App::class,
        'Auth'    => Illuminate\Support\Facades\Auth::class,
        'Cache'   => Illuminate\Support\Facades\Cache::class,
        'Config'  => Illuminate\Support\Facades\Config::class,
        'DB'      => Illuminate\Support\Facades\DB::class,
        'Hash'    => Illuminate\Support\Facades\Hash::class,
        'Http'    => Illuminate\Support\Facades\Http::class,
        'Log'     => Illuminate\Support\Facades\Log::class,
        'Route'   => Illuminate\Support\Facades\Route::class,
        'Schema'  => Illuminate\Support\Facades\Schema::class,
        'Storage' => Illuminate\Support\Facades\Storage::class,
        'URL'     => Illuminate\Support\Facades\URL::class,
        'Validator'=> Illuminate\Support\Facades\Validator::class,
        'JWTAuth' => PHPOpenSourceSaver\JWTAuth\Facades\JWTAuth::class,
    ],
];
