<?php

namespace Database\Seeders;

use App\Models\Driver;
use App\Models\User;
use App\Models\UserProfile;
use App\Models\Vehicle;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class FleetSeeder extends Seeder
{
    private array $vehicles = [
        [
            'make'       => 'Rolls-Royce',
            'model'      => 'Phantom VIII Extended',
            'year'       => 2024,
            'color'      => 'Andalusian White',
            'plate'      => 'VH-RR-001',
            'category'   => 'ultra_luxury',
            'capacity'   => 4,
            'hourly'     => 650.00,
            'daily'      => 4500.00,
            'airport'    => 280.00,
            'cover'      => 'https://images.unsplash.com/photo-1563720223523-f4ac96ef9a36?w=1200&q=90',
            'features'   => ['Starlight Headliner', 'Champagne Chiller', 'Privacy Glass', 'Bespoke Audio', 'Lambswool Carpets', 'Rear Massage Seats'],
        ],
        [
            'make'       => 'Mercedes-Benz',
            'model'      => 'Maybach S 680',
            'year'       => 2024,
            'color'      => 'Rubellite Red / Obsidian Black',
            'plate'      => 'VH-MB-002',
            'category'   => 'ultra_luxury',
            'capacity'   => 4,
            'hourly'     => 520.00,
            'daily'      => 3600.00,
            'airport'    => 220.00,
            'cover'      => 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=1200&q=90',
            'features'   => ['Executive Rear Suite', 'Burmester 4D Audio', 'Heated Rear Seats', 'MBUX Rear Tablet', 'Refrigerated Compartment', 'Privacy Curtains'],
        ],
        [
            'make'       => 'Bentley',
            'model'      => 'Flying Spur Mulliner',
            'year'       => 2023,
            'color'      => 'Cricket Ball Red',
            'plate'      => 'VH-BN-003',
            'category'   => 'ultra_luxury',
            'capacity'   => 4,
            'hourly'     => 480.00,
            'daily'      => 3400.00,
            'airport'    => 200.00,
            'cover'      => 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&q=90',
            'features'   => ['Diamond Quilted Leather', 'Naim for Bentley Audio', 'Rotating Display', 'Handcrafted Veneer', 'Massage Seats', 'Mood Lighting'],
        ],
        [
            'make'       => 'Range Rover',
            'model'      => 'Autobiography LWB',
            'year'       => 2024,
            'color'      => 'Carpathian Grey',
            'plate'      => 'VH-RV-004',
            'category'   => 'suv',
            'capacity'   => 5,
            'hourly'     => 380.00,
            'daily'      => 2800.00,
            'airport'    => 160.00,
            'cover'      => 'https://images.unsplash.com/photo-1584345604476-8ec5f82d72c7?w=1200&q=90',
            'features'   => ['Executive Class Seating', 'Meridian Signature Audio', 'All-Terrain Capability', 'Panoramic Roof', 'Heads-Up Display', 'Rear Entertainment'],
        ],
        [
            'make'       => 'Rolls-Royce',
            'model'      => 'Cullinan Black Badge',
            'year'       => 2024,
            'color'      => 'Black Diamond',
            'plate'      => 'VH-RC-005',
            'category'   => 'ultra_luxury',
            'capacity'   => 4,
            'hourly'     => 590.00,
            'daily'      => 4200.00,
            'airport'    => 260.00,
            'cover'      => 'https://images.unsplash.com/photo-1566473965997-3de9c817e938?w=1200&q=90',
            'features'   => ['Black Badge Treatment', 'Starlight Headliner', 'Bespoke Audio', 'Recreation Module', 'Illuminated Fascia', 'Privacy Glass'],
        ],
        [
            'make'       => 'Mercedes-AMG',
            'model'      => 'G 63 Edition 55',
            'year'       => 2023,
            'color'      => 'Designo Diamond White Bright',
            'plate'      => 'VH-AG-006',
            'category'   => 'suv',
            'capacity'   => 5,
            'hourly'     => 340.00,
            'daily'      => 2400.00,
            'airport'    => 140.00,
            'cover'      => 'https://images.unsplash.com/photo-1601362840469-51e4d8d58785?w=1200&q=90',
            'features'   => ['AMG Performance Pack', 'Burmester Surround Sound', 'Sport Exhaust', 'MBUX System', 'Night Package', 'Carbon Fibre Trim'],
        ],
        [
            'make'       => 'Bentley',
            'model'      => 'Bentayga EWB Azure',
            'year'       => 2024,
            'color'      => 'Onyx',
            'plate'      => 'VH-BA-007',
            'category'   => 'suv',
            'capacity'   => 5,
            'hourly'     => 420.00,
            'daily'      => 3000.00,
            'airport'    => 180.00,
            'cover'      => 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=1200&q=90',
            'features'   => ['Azure Specification', 'Ottoman Rear Seat', 'Airline Leg Rest', 'Rear Console Refrigerator', 'Naim Audio', 'Wellness Massager'],
        ],
        [
            'make'       => 'Lexus',
            'model'      => 'LM 500h Executive',
            'year'       => 2024,
            'color'      => 'Graphite Black Glass',
            'plate'      => 'VH-LX-008',
            'category'   => 'luxury',
            'capacity'   => 4,
            'hourly'     => 280.00,
            'daily'      => 2000.00,
            'airport'    => 120.00,
            'cover'      => 'https://images.unsplash.com/photo-1616422285623-13ff0162193c?w=1200&q=90',
            'features'   => ['Executive Lounge Seating', 'Rear Partition Wall', 'Air Purifier', 'Mark Levinson Premium Audio', 'Ottoman Footrests', 'Ambient Lighting'],
        ],
        [
            'make'       => 'Ferrari',
            'model'      => 'Roma Spider',
            'year'       => 2024,
            'color'      => 'Rosso Portofino',
            'plate'      => 'VH-FE-009',
            'category'   => 'sports',
            'capacity'   => 2,
            'hourly'     => 750.00,
            'daily'      => 5500.00,
            'airport'    => null,
            'cover'      => 'https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=1200&q=90',
            'features'   => ['V8 Turbo 620hp', 'Retractable Hard Top', 'Sport Exhaust', 'Apple CarPlay', 'Carbon Ceramic Brakes', 'Bespoke Interior'],
        ],
    ];

    private array $drivers = [
        [
            'vehicle_index' => 0,
            'first_name'    => 'Rustam',
            'last_name'     => 'Karimov',
            'email'         => 'rustam.k@velvet.driver',
            'license'       => 'UZ-DRV-001-RK',
            'experience'    => 12,
            'rating'        => 4.98,
            'languages'     => ['Uzbek', 'Russian', 'English'],
            'bio'           => 'Twelve years escorting heads of state and top executives across Central Asia. Defensive driving certified with crisis response training. Former Uzbekistan State Protocol Services.',
            'certifications'=> ['Defensive Driving (EVOC)', 'VIP Close Protection Level 2', 'First Aid'],
            'avatar'        => 'https://images.unsplash.com/photo-1607990281513-2c110a25bd8c?w=400&q=90',
        ],
        [
            'vehicle_index' => 1,
            'first_name'    => 'Sergey',
            'last_name'     => 'Petrov',
            'email'         => 'sergey.p@velvet.driver',
            'license'       => 'UZ-DRV-002-SP',
            'experience'    => 15,
            'rating'        => 4.96,
            'languages'     => ['Russian', 'English', 'Uzbek', 'German'],
            'bio'           => 'Former chauffeur for the German Embassy in Tashkent. 15 years of impeccable service with a philosophy of invisible presence and maximum discretion. Knows every route in Tashkent and Almaty.',
            'certifications'=> ['Defensive Driving (EVOC)', 'VIP Protocol Training Germany', 'CCTV & Route Planning'],
            'avatar'        => 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=90',
        ],
        [
            'vehicle_index' => 2,
            'first_name'    => 'Mirzo',
            'last_name'     => 'Toshmatov',
            'email'         => 'mirzo.t@velvet.driver',
            'license'       => 'UZ-DRV-003-MT',
            'experience'    => 9,
            'rating'        => 4.95,
            'languages'     => ['Uzbek', 'Russian', 'English', 'Tajik'],
            'bio'           => 'Graduated from the National Driver Excellence Institute and served as a presidential motorcade support driver for three years. Exceptionally calm under pressure with flawless navigation skills.',
            'certifications'=> ['Executive Protection Driving', 'Presidential Motorcade Support', 'Multi-Language Client Protocol'],
            'avatar'        => 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=400&q=90',
        ],
        [
            'vehicle_index' => 3,
            'first_name'    => 'James',
            'last_name'     => 'Okafor',
            'email'         => 'james.o@velvet.driver',
            'license'       => 'UZ-DRV-004-JO',
            'experience'    => 11,
            'rating'        => 4.97,
            'languages'     => ['English', 'French', 'Yoruba', 'Russian'],
            'bio'           => 'Former Royal Household chauffeur based in London, James relocated to Tashkent following a private fleet management opportunity. His impeccable English manners and multi-lingual fluency make him the top choice for international VIP clients.',
            'certifications'=> ['Royal Household Chauffeur Standard', 'IAM Advanced Driver', 'French Embassy Protocol'],
            'avatar'        => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=90',
        ],
        [
            'vehicle_index' => 4,
            'first_name'    => 'Akbar',
            'last_name'     => 'Yusupov',
            'email'         => 'akbar.y@velvet.driver',
            'license'       => 'UZ-DRV-005-AY',
            'experience'    => 8,
            'rating'        => 4.93,
            'languages'     => ['Uzbek', 'Russian', 'English', 'Arabic'],
            'bio'           => 'Arabic-speaking VIP driver with deep expertise in serving Gulf-state clients. Trained in Islamic etiquette for client interactions, prayer-time route planning, and halal dining recommendations across Tashkent.',
            'certifications'=> ['VIP Protocol — GCC Standards', 'Arabic Client Etiquette', 'Defensive Driving (EVOC)'],
            'avatar'        => 'https://images.unsplash.com/photo-1556474835-b0f3ac40d4d1?w=400&q=90',
        ],
        [
            'vehicle_index' => 5,
            'first_name'    => 'Viktor',
            'last_name'     => 'Morozov',
            'email'         => 'viktor.m@velvet.driver',
            'license'       => 'UZ-DRV-006-VM',
            'experience'    => 14,
            'rating'        => 4.94,
            'languages'     => ['Russian', 'Uzbek', 'English'],
            'bio'           => 'Ex-special forces with an immaculate driving record across 30+ countries. Viktor\'s situational awareness and calm demeanour make him invaluable for high-security engagements. Holds a current CBRN (Chemical, Biological, Radiological, Nuclear) Awareness certificate.',
            'certifications'=> ['Special Forces Driver Training', 'CBRN Awareness', 'Executive Close Protection Level 3'],
            'avatar'        => 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=90',
        ],
        [
            'vehicle_index' => 6,
            'first_name'    => 'Chen',
            'last_name'     => 'Wei',
            'email'         => 'chen.w@velvet.driver',
            'license'       => 'UZ-DRV-007-CW',
            'experience'    => 7,
            'rating'        => 4.91,
            'languages'     => ['Mandarin', 'English', 'Russian', 'Cantonese'],
            'bio'           => 'Mandarin-speaking chauffeur who has served Beijing and Shanghai luxury hotel concierge fleets before joining VelvetHour Tashkent. Specialises in serving Chinese and East Asian clients with culturally attuned service standards.',
            'certifications'=> ['China National Chauffeur Excellence', 'Luxury Hotel Concierge Driver Standard', 'VIP Client Protocol'],
            'avatar'        => 'https://images.unsplash.com/photo-1603415526960-f7e0328c63b1?w=400&q=90',
        ],
        [
            'vehicle_index' => 7,
            'first_name'    => 'Hamid',
            'last_name'     => 'Nazarov',
            'email'         => 'hamid.n@velvet.driver',
            'license'       => 'UZ-DRV-008-HN',
            'experience'    => 10,
            'rating'        => 4.92,
            'languages'     => ['Uzbek', 'Tajik', 'Russian', 'English', 'Farsi'],
            'bio'           => 'Farsi and Tajik-speaking driver with extensive experience serving Iranian and Afghan diplomatic families. Expert knowledge of border formalities, regional road networks, and cross-cultural client service. Reliable beyond measure.',
            'certifications'=> ['Diplomatic Chauffeur Certification', 'Cross-Border Logistics', 'Farsi & Tajik Client Protocol'],
            'avatar'        => 'https://images.unsplash.com/photo-1542178243-bc20204b769f?w=400&q=90',
        ],
        [
            'vehicle_index' => 8,
            'first_name'    => 'Lorenzo',
            'last_name'     => 'Ferrari',
            'email'         => 'lorenzo.f@velvet.driver',
            'license'       => 'UZ-DRV-009-LF',
            'experience'    => 6,
            'rating'        => 4.99,
            'languages'     => ['Italian', 'English', 'French', 'Spanish'],
            'bio'           => 'A former Ferrari factory test driver and Scuderia Ferrari hospitality driver, Lorenzo brings motorsport-level precision to every journey. Available exclusively with the Roma Spider. His knowledge of supercars and track dynamics creates an unparalleled experience.',
            'certifications'=> ['Ferrari Factory Driver Programme', 'FIA Advanced Racing Licence', 'Concierge Driving Excellence Italy'],
            'avatar'        => 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=400&q=90',
        ],
    ];

    public function run(): void
    {
        $vehicleIds = [];

        foreach ($this->vehicles as $v) {
            $vehicle = Vehicle::create([
                'make'                => $v['make'],
                'model'               => $v['model'],
                'year'                => $v['year'],
                'color'               => $v['color'],
                'license_plate'       => $v['plate'],
                'category'            => $v['category'],
                'passenger_capacity'  => $v['capacity'],
                'hourly_rate'         => $v['hourly'],
                'daily_rate'          => $v['daily'],
                'airport_transfer_rate' => $v['airport'],
                'cover_image_url'     => $v['cover'],
                'features'            => $v['features'],
                'status'              => 'available',
                'rating'              => round(4.88 + mt_rand(0, 12) / 100, 2),
            ]);
            $vehicleIds[] = $vehicle->id;
        }

        foreach ($this->drivers as $d) {
            $user = User::create([
                'email'          => $d['email'],
                'password'       => Hash::make('VelvetDriver2024!'),
                'role'           => 'driver',
                'status'         => 'active',
                'email_verified' => true,
            ]);

            UserProfile::create([
                'user_id'    => $user->id,
                'first_name' => $d['first_name'],
                'last_name'  => $d['last_name'],
                'avatar_url' => $d['avatar'],
                'city'       => 'Tashkent',
                'country'    => 'Uzbekistan',
            ]);

            Driver::create([
                'user_id'        => $user->id,
                'vehicle_id'     => $vehicleIds[$d['vehicle_index']],
                'license_number' => $d['license'],
                'experience_years' => $d['experience'],
                'rating'         => $d['rating'],
                'total_trips'    => rand(80, 400),
                'languages'      => $d['languages'],
                'is_available'   => true,
                'is_verified'    => true,
                'avatar_url'     => $d['avatar'],
                'bio'            => $d['bio'],
                'certifications' => $d['certifications'],
            ]);
        }

        $this->command->info('✓ Seeded 9 luxury vehicles and 9 elite drivers');
    }
}
